
// CppConstants.cs - generated by the SLK parser generator 

namespace Dsl.Parser
{

class CppConstants {

public const short  LPAREN_ = 1;
public const short  RPAREN_ = 2;
public const short  LBRACK_ = 3;
public const short  RBRACK_ = 4;
public const short  COLON_COLON_ = 5;
public const short  DOT_ = 6;
public const short  POINTER_ = 7;
public const short  PERIOD_STAR_ = 8;
public const short  POINTER_STAR_ = 9;
public const short  LBRACE_ = 10;
public const short  RBRACE_ = 11;
public const short  BRACKET_COLON_BEGIN_ = 12;
public const short  BRACKET_COLON_END_ = 13;
public const short  ANGLE_BRACKET_COLON_BEGIN_ = 14;
public const short  ANGLE_BRACKET_COLON_END_ = 15;
public const short  ANGLE_BRACKET_PERCENT_BEGIN_ = 16;
public const short  ANGLE_BRACKET_PERCENT_END_ = 17;
public const short  IDENTIFIER_ = 18;
public const short  STRING_ = 19;
public const short  NUMBER_ = 20;
public const short  COMMA_ = 21;
public const short  SEMI_ = 22;
public const short  END_OF_SLK_INPUT_ = 23;


public const short  NT_PROGRAM_ = 24;
public const short  NT_STATEMENTS_ = 25;
public const short  NT_STATEMENT_ = 26;
public const short  NT_FUNCTION_STATEMENT_ = 27;
public const short  NT_FUNCTION_STATEMENT_DESC_ = 28;
public const short  NT_FUNCTION_CALLS_ = 29;
public const short  NT_FUNCTION_EX_CALL_ = 30;
public const short  NT_FUNCTION_EX_CALL_SPECIAL_ = 31;
public const short  NT_FUNCTION_PARAMS_ = 32;
public const short  NT_STATIC_MEMBER_DESC_ = 33;
public const short  NT_MEMBER_DESC_ = 34;
public const short  NT_MEMBER_DESC2_ = 35;
public const short  NT_MEMBER_DESC3_ = 36;
public const short  NT_MEMBER_DESC4_ = 37;
public const short  NT_FUNCTION_ID_ = 38;
public const short  NT_SEP_ = 39;
public const short  NT_SEP_STATEMENT_STAR_ = 40;
public const short  NT_FUNCTION_EX_CALL_STAR_ = 41;
public const short  NT_FUNCTION_EX_CALL_2_STAR_ = 42;
public const short  NT_FUNCTION_PARAMS_OPT_ = 43;
public const short  NT_FUNCTION_PARAMS_2_OPT_ = 44;
public const short  NT_FUNCTION_PARAMS_3_OPT_ = 45;
public const short  NT_FUNCTION_PARAMS_4_OPT_ = 46;
public const short  NT_FUNCTION_PARAMS_5_OPT_ = 47;
public const short  NT_FUNCTION_PARAMS_6_OPT_ = 48;
public const short  NT_FUNCTION_PARAMS_7_OPT_ = 49;
public const short  NT_FUNCTION_PARAMS_8_OPT_ = 50;
public const short  NT_FUNCTION_PARAMS_9_OPT_ = 51;
public const short  NT_FUNCTION_PARAMS_10_OPT_ = 52;
public const short  NT_FUNCTION_PARAMS_11_OPT_ = 53;
public const short  NT_FUNCTION_PARAMS_12_OPT_ = 54;


};


}