
// CppConstants.cs - generated by the SLK parser generator 

namespace Dsl.Parser {

class CppConstants {

public const short  LPAREN_ = 1;
public const short  RPAREN_ = 2;
public const short  LBRACK_ = 3;
public const short  RBRACK_ = 4;
public const short  LBRACE_ = 5;
public const short  RBRACE_ = 6;
public const short  IDENTIFIER_ = 7;
public const short  STRING_ = 8;
public const short  NUMBER_ = 9;
public const short  COMMA_ = 10;
public const short  SEMI_ = 11;
public const short  END_OF_SLK_INPUT_ = 12;


public const short  NT_PROGRAM_ = 13;
public const short  NT_STATEMENTS_ = 14;
public const short  NT_STATEMENT_ = 15;
public const short  NT_FUNCTION_STATEMENT_ = 16;
public const short  NT_FUNCTION_STATEMENT_DESC_ = 17;
public const short  NT_FUNCTION_CALLS_ = 18;
public const short  NT_FUNCTION_EX_CALL_ = 19;
public const short  NT_FUNCTION_EX_CALL_SPECIAL_ = 20;
public const short  NT_FUNCTION_PARAMS_ = 21;
public const short  NT_FUNCTION_ID_ = 22;
public const short  NT_SEP_ = 23;
public const short  NT_SEP_STATEMENT_STAR_ = 24;
public const short  NT_FUNCTION_EX_CALL_STAR_ = 25;
public const short  NT_FUNCTION_EX_CALL_2_STAR_ = 26;
public const short  NT_FUNCTION_PARAMS_OPT_ = 27;
public const short  NT_FUNCTION_PARAMS_2_OPT_ = 28;
public const short  NT_FUNCTION_PARAMS_3_OPT_ = 29;
public const short  NT_FUNCTION_PARAMS_4_OPT_ = 30;


};


}