
// CppString.cs - generated by the SLK parser generator 

namespace Dsl.Parser {

class CppString {

private static string[] Nonterminal_name ={"0"

,"PROGRAM"
,"STATEMENTS"
,"STATEMENT"
,"FUNCTION_STATEMENT"
,"FUNCTION_STATEMENT_DESC"
,"FUNCTION_CALLS"
,"FUNCTION_EX_CALL"
,"FUNCTION_EX_CALL_SPECIAL"
,"FUNCTION_PARAMS"
,"FUNCTION_ID"
,"SEP"
,"SEP_STATEMENT_*"
,"FUNCTION_EX_CALL_*"
,"FUNCTION_EX_CALL_2_*"
,"FUNCTION_PARAMS_opt"
,"FUNCTION_PARAMS_2_opt"
,"FUNCTION_PARAMS_3_opt"
,"FUNCTION_PARAMS_4_opt"
};

private static string[] Terminal_name ={"0"

,"("
,")"
,"["
,"]"
,"{"
,"}"
,"IDENTIFIER"
,"STRING"
,"NUMBER"
,","
,";"
,"END_OF_SLK_INPUT"
};

private static string[] Action_name ={"0"

,"_action_markSeparator"
,"_action_endStatement"
,"_action_beginStatement"
,"_action_cppOnFunctionBegin"
,"_action_addFunction"
,"_action_cppOnFunctionEnd"
,"_action_setFunctionId"
,"_action_markParenthesisParam"
,"_action_buildHighOrderFunction"
,"_action_markBracketParam"
,"_action_markStatement"
,"_action_pushId"
,"_action_pushStr"
,"_action_pushNum"
,"_action_pushComma"
,"_action_pushSemiColon"
};

private static string[] Production_name ={"0"

,"PROGRAM --> STATEMENTS"
,"STATEMENTS --> STATEMENT SEP_STATEMENT_*"
,"STATEMENT --> FUNCTION_STATEMENT"
,"FUNCTION_STATEMENT --> FUNCTION_STATEMENT_DESC _action_endStatement"
,"FUNCTION_STATEMENT_DESC --> _action_beginStatement FUNCTION_CALLS"
,"FUNCTION_CALLS --> FUNCTION_EX_CALL_*"
,"FUNCTION_CALLS --> _action_cppOnFunctionBegin _action_addFunction FUNCTION_EX_CALL_SPECIAL _action_cppOnFunctionEnd FUNCTION_EX_CALL_2_*"
,"FUNCTION_EX_CALL --> FUNCTION_ID _action_setFunctionId FUNCTION_PARAMS_opt"
,"FUNCTION_EX_CALL_SPECIAL --> FUNCTION_PARAMS"
,"FUNCTION_PARAMS --> _action_markParenthesisParam ( STATEMENTS ) FUNCTION_PARAMS_2_opt"
,"FUNCTION_PARAMS --> _action_markBracketParam [ STATEMENTS ] FUNCTION_PARAMS_3_opt"
,"FUNCTION_PARAMS --> _action_markStatement { STATEMENTS } FUNCTION_PARAMS_4_opt"
,"FUNCTION_ID --> IDENTIFIER _action_pushId"
,"FUNCTION_ID --> STRING _action_pushStr"
,"FUNCTION_ID --> NUMBER _action_pushNum"
,"SEP --> , _action_pushComma"
,"SEP --> ; _action_pushSemiColon"
,"SEP_STATEMENT_* --> SEP _action_markSeparator STATEMENT SEP_STATEMENT_*"
,"SEP_STATEMENT_* -->"
,"FUNCTION_EX_CALL_* --> _action_cppOnFunctionBegin _action_addFunction FUNCTION_EX_CALL _action_cppOnFunctionEnd FUNCTION_EX_CALL_*"
,"FUNCTION_EX_CALL_* -->"
,"FUNCTION_EX_CALL_2_* --> _action_cppOnFunctionBegin _action_addFunction FUNCTION_EX_CALL _action_cppOnFunctionEnd FUNCTION_EX_CALL_2_*"
,"FUNCTION_EX_CALL_2_* -->"
,"FUNCTION_PARAMS_opt --> FUNCTION_PARAMS"
,"FUNCTION_PARAMS_opt -->"
,"FUNCTION_PARAMS_2_opt --> _action_buildHighOrderFunction FUNCTION_PARAMS"
,"FUNCTION_PARAMS_2_opt -->"
,"FUNCTION_PARAMS_3_opt --> _action_buildHighOrderFunction FUNCTION_PARAMS"
,"FUNCTION_PARAMS_3_opt -->"
,"FUNCTION_PARAMS_4_opt --> _action_buildHighOrderFunction FUNCTION_PARAMS"
,"FUNCTION_PARAMS_4_opt -->"
};

private const short   START_SYMBOL = 13;
private const short   START_ACTION = 31;
private const short   END_ACTION = 47;

public static string  GetSymbolName ( short symbol )
{
  if ( symbol >= START_ACTION && symbol < END_ACTION ) {
      return ( Action_name [symbol - (START_ACTION-1)] );
  } else if ( symbol >= START_SYMBOL ) {
      return ( Nonterminal_name [symbol - (START_SYMBOL-1)] );
  } else if ( symbol > 0 ) {
      return ( Terminal_name [ symbol ] );
  }
  return ( "not a symbol" );
}

public static string  GetProductionName ( short production_number )
{
  return ( Production_name [production_number] );
}


};


}