#if FULL_VERSION
// DslConstants.cs - generated by the SLK parser generator 
namespace Dsl.Parser
{

    class DslConstants
    {

        internal const short OP_TOKEN_0_ = 1;
        internal const short OP_TOKEN_1_ = 2;
        internal const short OP_TOKEN_2_ = 3;
        internal const short OP_TOKEN_3_ = 4;
        internal const short OP_TOKEN_4_ = 5;
        internal const short OP_TOKEN_5_ = 6;
        internal const short OP_TOKEN_6_ = 7;
        internal const short OP_TOKEN_7_ = 8;
        internal const short OP_TOKEN_8_ = 9;
        internal const short OP_TOKEN_9_ = 10;
        internal const short OP_TOKEN_10_ = 11;
        internal const short OP_TOKEN_11_ = 12;
        internal const short OP_TOKEN_12_ = 13;
        internal const short LBRACE_ = 14;
        internal const short RBRACE_ = 15;
        internal const short SCRIPT_CONTENT_ = 16;
        internal const short LPAREN_ = 17;
        internal const short RPAREN_ = 18;
        internal const short LBRACK_ = 19;
        internal const short RBRACK_ = 20;
        internal const short DOT_ = 21;
        internal const short IDENTIFIER_ = 22;
        internal const short STRING_ = 23;
        internal const short NUMBER_ = 24;
        internal const short TRUE_ = 25;
        internal const short FALSE_ = 26;
        internal const short COMMA_ = 27;
        internal const short SEMI_ = 28;
        internal const short END_OF_SLK_INPUT_ = 29;


        internal const short NT_PROGRAM_ = 30;
        internal const short NT_STATEMENTS_ = 31;
        internal const short NT_STATEMENT_ = 32;
        internal const short NT_OPERATOR_STATEMENT_1_ = 33;
        internal const short NT_OPERATOR_STATEMENT_2_ = 34;
        internal const short NT_OPERATOR_STATEMENT_3_ = 35;
        internal const short NT_OPERATOR_STATEMENT_4_ = 36;
        internal const short NT_OPERATOR_STATEMENT_5_ = 37;
        internal const short NT_OPERATOR_STATEMENT_6_ = 38;
        internal const short NT_OPERATOR_STATEMENT_7_ = 39;
        internal const short NT_OPERATOR_STATEMENT_8_ = 40;
        internal const short NT_OPERATOR_STATEMENT_9_ = 41;
        internal const short NT_OPERATOR_STATEMENT_10_ = 42;
        internal const short NT_OPERATOR_STATEMENT_11_ = 43;
        internal const short NT_OPERATOR_STATEMENT_12_ = 44;
        internal const short NT_OPERATOR_STATEMENT_DESC_0_ = 45;
        internal const short NT_OPERATOR_STATEMENT_DESC_1_ = 46;
        internal const short NT_OPERATOR_STATEMENT_DESC_2_ = 47;
        internal const short NT_OPERATOR_STATEMENT_DESC_3_ = 48;
        internal const short NT_OPERATOR_STATEMENT_DESC_4_ = 49;
        internal const short NT_OPERATOR_STATEMENT_DESC_5_ = 50;
        internal const short NT_OPERATOR_STATEMENT_DESC_6_ = 51;
        internal const short NT_OPERATOR_STATEMENT_DESC_7_ = 52;
        internal const short NT_OPERATOR_STATEMENT_DESC_8_ = 53;
        internal const short NT_OPERATOR_STATEMENT_DESC_9_ = 54;
        internal const short NT_OPERATOR_STATEMENT_DESC_10_ = 55;
        internal const short NT_OPERATOR_STATEMENT_DESC_11_ = 56;
        internal const short NT_OPERATOR_STATEMENT_DESC_12_ = 57;
        internal const short NT_FUNCTION_STATEMENT_ = 58;
        internal const short NT_FUNCTION_STATEMENT_DESC_ = 59;
        internal const short NT_FUNCTION_CALLS_ = 60;
        internal const short NT_FUNCTION_EX_CALL_ = 61;
        internal const short NT_FUNCTION_EX_CALL_SPECIAL_ = 62;
        internal const short NT_FUNCTION_EX_ = 63;
        internal const short NT_FUNCTION_PARAMS_ = 64;
        internal const short NT_MEMBER_DESC_ = 65;
        internal const short NT_FUNCTION_ID_ = 66;
        internal const short NT_SEP_ = 67;
        internal const short NT_SEP_STATEMENT_STAR_ = 68;
        internal const short NT_OP_TOKEN_0_OPERATOR_STATEMENT_1_STAR_ = 69;
        internal const short NT_OP_TOKEN_1_OPERATOR_STATEMENT_2_OP_TOKEN_1_OPERATOR_STATEMENT_2_STAR_ = 70;
        internal const short NT_OP_TOKEN_2_OPERATOR_STATEMENT_3_STAR_ = 71;
        internal const short NT_OP_TOKEN_3_OPERATOR_STATEMENT_4_STAR_ = 72;
        internal const short NT_OP_TOKEN_4_OPERATOR_STATEMENT_5_STAR_ = 73;
        internal const short NT_OP_TOKEN_5_OPERATOR_STATEMENT_6_STAR_ = 74;
        internal const short NT_OP_TOKEN_6_OPERATOR_STATEMENT_7_STAR_ = 75;
        internal const short NT_OP_TOKEN_7_OPERATOR_STATEMENT_8_STAR_ = 76;
        internal const short NT_OP_TOKEN_8_OPERATOR_STATEMENT_9_STAR_ = 77;
        internal const short NT_OP_TOKEN_9_OPERATOR_STATEMENT_10_STAR_ = 78;
        internal const short NT_OP_TOKEN_10_OPERATOR_STATEMENT_11_STAR_ = 79;
        internal const short NT_OP_TOKEN_11_OPERATOR_STATEMENT_12_STAR_ = 80;
        internal const short NT_OP_TOKEN_12_FUNCTION_STATEMENT_STAR_ = 81;
        internal const short NT_FUNCTION_EX_CALL_STAR_ = 82;
        internal const short NT_FUNCTION_PARAMS_OPT_ = 83;
        internal const short NT_FUNCTION_EX_OPT_ = 84;
        internal const short NT_FUNCTION_EX_2_OPT_ = 85;
        internal const short NT_FUNCTION_PARAMS_2_OPT_ = 86;
        internal const short NT_FUNCTION_PARAMS_3_OPT_ = 87;
        internal const short NT_FUNCTION_PARAMS_4_OPT_ = 88;

    };

}
#endif