
// SlkString.h - generated by the SLK parser generator 

#ifndef _SlkSTRING_H
#define _SlkSTRING_H

const char *SlkGetSymbolName ( unsigned int   symbol );
const char *SlkGetProductionName ( unsigned int  production_number );


#endif
