
// DslConstants.cs - generated by the SLK parser generator 

namespace Dsl.Parser
{

    class DslConstants
    {

public const short  OP_TOKEN_0_ = 1;
public const short  OP_TOKEN_1_ = 2;
public const short  OP_TOKEN_2_ = 3;
public const short  OP_TOKEN_COLON_ = 4;
public const short  OP_TOKEN_QUESTION_ = 5;
public const short  OP_TOKEN_3_ = 6;
public const short  OP_TOKEN_4_ = 7;
public const short  OP_TOKEN_5_ = 8;
public const short  OP_TOKEN_6_ = 9;
public const short  OP_TOKEN_7_ = 10;
public const short  OP_TOKEN_8_ = 11;
public const short  OP_TOKEN_9_ = 12;
public const short  OP_TOKEN_10_ = 13;
public const short  OP_TOKEN_11_ = 14;
public const short  OP_TOKEN_12_ = 15;
public const short  OP_TOKEN_13_ = 16;
public const short  OP_TOKEN_14_ = 17;
public const short  OP_TOKEN_15_ = 18;
public const short  LPAREN_ = 19;
public const short  RPAREN_ = 20;
public const short  LBRACK_ = 21;
public const short  RBRACK_ = 22;
public const short  COLON_COLON_ = 23;
public const short  DOT_ = 24;
public const short  QUESTION_PERIOD_ = 25;
public const short  QUESTION_PARENTHESIS_ = 26;
public const short  QUESTION_BRACKET_ = 27;
public const short  QUESTION_BRACE_ = 28;
public const short  RBRACE_ = 29;
public const short  POINTER_ = 30;
public const short  PERIOD_STAR_ = 31;
public const short  QUESTION_PERIOD_STAR_ = 32;
public const short  POINTER_STAR_ = 33;
public const short  LBRACE_ = 34;
public const short  SCRIPT_CONTENT_ = 35;
public const short  BRACKET_COLON_BEGIN_ = 36;
public const short  BRACKET_COLON_END_ = 37;
public const short  PARENTHESIS_COLON_BEGIN_ = 38;
public const short  PARENTHESIS_COLON_END_ = 39;
public const short  ANGLE_BRACKET_COLON_BEGIN_ = 40;
public const short  ANGLE_BRACKET_COLON_END_ = 41;
public const short  BRACE_PERCENT_BEGIN_ = 42;
public const short  BRACE_PERCENT_END_ = 43;
public const short  BRACKET_PERCENT_BEGIN_ = 44;
public const short  BRACKET_PERCENT_END_ = 45;
public const short  PARENTHESIS_PERCENT_BEGIN_ = 46;
public const short  PARENTHESIS_PERCENT_END_ = 47;
public const short  ANGLE_BRACKET_PERCENT_BEGIN_ = 48;
public const short  ANGLE_BRACKET_PERCENT_END_ = 49;
public const short  IDENTIFIER_ = 50;
public const short  STRING_ = 51;
public const short  NUMBER_ = 52;
public const short  COMMA_ = 53;
public const short  SEMI_ = 54;
public const short  END_OF_SLK_INPUT_ = 55;


public const short  NT_PROGRAM_ = 56;
public const short  NT_STATEMENTS_ = 57;
public const short  NT_STATEMENT_ = 58;
public const short  NT_OPERATOR_STATEMENT_0_ = 59;
public const short  NT_OPERATOR_STATEMENT_1_ = 60;
public const short  NT_OPERATOR_STATEMENT_COLON_ = 61;
public const short  NT_OPERATOR_STATEMENT_QUESTION_COLON_ = 62;
public const short  NT_OPERATOR_STATEMENT_4_ = 63;
public const short  NT_OPERATOR_STATEMENT_5_ = 64;
public const short  NT_OPERATOR_STATEMENT_6_ = 65;
public const short  NT_OPERATOR_STATEMENT_7_ = 66;
public const short  NT_OPERATOR_STATEMENT_8_ = 67;
public const short  NT_OPERATOR_STATEMENT_9_ = 68;
public const short  NT_OPERATOR_STATEMENT_10_ = 69;
public const short  NT_OPERATOR_STATEMENT_11_ = 70;
public const short  NT_OPERATOR_STATEMENT_12_ = 71;
public const short  NT_OPERATOR_STATEMENT_13_ = 72;
public const short  NT_OPERATOR_STATEMENT_14_ = 73;
public const short  NT_OPERATOR_STATEMENT_15_ = 74;
public const short  NT_OPERATOR_STATEMENT_DESC_0_ = 75;
public const short  NT_OPERATOR_STATEMENT_DESC_1_ = 76;
public const short  NT_OPERATOR_STATEMENT_DESC_2_ = 77;
public const short  NT_OPERATOR_STATEMENT_DESC_COLON_ = 78;
public const short  NT_OPERATOR_STATEMENT_DESC_QUESTION_COLON_ = 79;
public const short  NT_OPERATOR_STATEMENT_DESC_3_ = 80;
public const short  NT_OPERATOR_STATEMENT_DESC_4_ = 81;
public const short  NT_OPERATOR_STATEMENT_DESC_5_ = 82;
public const short  NT_OPERATOR_STATEMENT_DESC_6_ = 83;
public const short  NT_OPERATOR_STATEMENT_DESC_7_ = 84;
public const short  NT_OPERATOR_STATEMENT_DESC_8_ = 85;
public const short  NT_OPERATOR_STATEMENT_DESC_9_ = 86;
public const short  NT_OPERATOR_STATEMENT_DESC_10_ = 87;
public const short  NT_OPERATOR_STATEMENT_DESC_11_ = 88;
public const short  NT_OPERATOR_STATEMENT_DESC_12_ = 89;
public const short  NT_OPERATOR_STATEMENT_DESC_13_ = 90;
public const short  NT_OPERATOR_STATEMENT_DESC_14_ = 91;
public const short  NT_OPERATOR_STATEMENT_DESC_15_ = 92;
public const short  NT_FUNCTION_STATEMENT_ = 93;
public const short  NT_FUNCTION_STATEMENT_DESC_ = 94;
public const short  NT_FUNCTION_CALLS_ = 95;
public const short  NT_FUNCTION_EX_CALL_ = 96;
public const short  NT_FUNCTION_EX_CALL_SPECIAL_ = 97;
public const short  NT_FUNCTION_PARAMS_ = 98;
public const short  NT_STATIC_MEMBER_DESC_ = 99;
public const short  NT_MEMBER_DESC_ = 100;
public const short  NT_MEMBER_DESC2_ = 101;
public const short  NT_MEMBER_DESC3_ = 102;
public const short  NT_MEMBER_DESC4_ = 103;
public const short  NT_MEMBER_DESC5_ = 104;
public const short  NT_MEMBER_DESC6_ = 105;
public const short  NT_FUNCTION_ID_ = 106;
public const short  NT_SEP_ = 107;
public const short  NT_SEP_STATEMENT_STAR_ = 108;
public const short  NT_OP_TOKEN_0_OPERATOR_STATEMENT_0_OPT_ = 109;
public const short  NT_OP_TOKEN_1_OPERATOR_STATEMENT_1_OPT_ = 110;
public const short  NT_OP_TOKEN_2_OPERATOR_STATEMENT_COLON_STAR_ = 111;
public const short  NT_OP_TOKEN_COLON_OPERATOR_STATEMENT_QUESTION_COLON_STAR_ = 112;
public const short  NT_OP_TOKEN_QUESTION_OPERATOR_STATEMENT_QUESTION_COLON_OP_TOKEN_COLON_OPERATOR_STATEMENT_QUESTION_COLON_OPT_ = 113;
public const short  NT_OP_TOKEN_3_OPERATOR_STATEMENT_4_STAR_ = 114;
public const short  NT_OP_TOKEN_4_OPERATOR_STATEMENT_5_STAR_ = 115;
public const short  NT_OP_TOKEN_5_OPERATOR_STATEMENT_6_STAR_ = 116;
public const short  NT_OP_TOKEN_6_OPERATOR_STATEMENT_7_STAR_ = 117;
public const short  NT_OP_TOKEN_7_OPERATOR_STATEMENT_8_STAR_ = 118;
public const short  NT_OP_TOKEN_8_OPERATOR_STATEMENT_9_STAR_ = 119;
public const short  NT_OP_TOKEN_9_OPERATOR_STATEMENT_10_STAR_ = 120;
public const short  NT_OP_TOKEN_10_OPERATOR_STATEMENT_11_STAR_ = 121;
public const short  NT_OP_TOKEN_11_OPERATOR_STATEMENT_12_STAR_ = 122;
public const short  NT_OP_TOKEN_12_OPERATOR_STATEMENT_13_STAR_ = 123;
public const short  NT_OP_TOKEN_13_OPERATOR_STATEMENT_14_STAR_ = 124;
public const short  NT_OP_TOKEN_14_OPERATOR_STATEMENT_15_STAR_ = 125;
public const short  NT_OP_TOKEN_15_FUNCTION_STATEMENT_STAR_ = 126;
public const short  NT_FUNCTION_EX_CALL_STAR_ = 127;
public const short  NT_FUNCTION_EX_CALL_2_STAR_ = 128;
public const short  NT_FUNCTION_PARAMS_OPT_ = 129;
public const short  NT_FUNCTION_PARAMS_2_OPT_ = 130;
public const short  NT_FUNCTION_PARAMS_3_OPT_ = 131;
public const short  NT_FUNCTION_PARAMS_4_OPT_ = 132;
public const short  NT_FUNCTION_PARAMS_5_OPT_ = 133;
public const short  NT_FUNCTION_PARAMS_6_OPT_ = 134;
public const short  NT_FUNCTION_PARAMS_7_OPT_ = 135;
public const short  NT_FUNCTION_PARAMS_8_OPT_ = 136;
public const short  NT_FUNCTION_PARAMS_9_OPT_ = 137;
public const short  NT_FUNCTION_PARAMS_10_OPT_ = 138;
public const short  NT_FUNCTION_PARAMS_11_OPT_ = 139;
public const short  NT_FUNCTION_PARAMS_12_OPT_ = 140;
public const short  NT_FUNCTION_PARAMS_13_OPT_ = 141;
public const short  NT_FUNCTION_PARAMS_14_OPT_ = 142;
public const short  NT_FUNCTION_PARAMS_15_OPT_ = 143;
public const short  NT_FUNCTION_PARAMS_16_OPT_ = 144;
public const short  NT_FUNCTION_PARAMS_17_OPT_ = 145;
public const short  NT_FUNCTION_PARAMS_18_OPT_ = 146;
public const short  NT_FUNCTION_PARAMS_19_OPT_ = 147;
public const short  NT_FUNCTION_PARAMS_20_OPT_ = 148;
public const short  NT_FUNCTION_PARAMS_21_OPT_ = 149;
public const short  NT_FUNCTION_PARAMS_22_OPT_ = 150;


};


}