
// DslConstants.cs - generated by the SLK parser generator

namespace Dsl.Parser
{

    class DslConstants
    {

public const short  OP_TOKEN_0_ = 1;
public const short  OP_TOKEN_1_ = 2;
public const short  OP_TOKEN_QUESTION_ = 3;
public const short  OP_TOKEN_QUESTION_COLON_ = 4;
public const short  OP_TOKEN_2_ = 5;
public const short  OP_TOKEN_COLON_ = 6;
public const short  OP_TOKEN_3_ = 7;
public const short  OP_TOKEN_4_ = 8;
public const short  OP_TOKEN_5_ = 9;
public const short  OP_TOKEN_6_ = 10;
public const short  OP_TOKEN_7_ = 11;
public const short  OP_TOKEN_8_ = 12;
public const short  OP_TOKEN_9_ = 13;
public const short  OP_TOKEN_10_ = 14;
public const short  OP_TOKEN_11_ = 15;
public const short  OP_TOKEN_12_ = 16;
public const short  OP_TOKEN_13_ = 17;
public const short  OP_TOKEN_14_ = 18;
public const short  OP_TOKEN_15_ = 19;
public const short  OP_TOKEN_NULLABLE_ = 20;
public const short  LPAREN_ = 21;
public const short  RPAREN_ = 22;
public const short  LBRACK_ = 23;
public const short  RBRACK_ = 24;
public const short  LBRACE_ = 25;
public const short  RBRACE_ = 26;
public const short  SCRIPT_CONTENT_ = 27;
public const short  BRACKET_COLON_BEGIN_ = 28;
public const short  BRACKET_COLON_END_ = 29;
public const short  PARENTHESES_COLON_BEGIN_ = 30;
public const short  PARENTHESES_COLON_END_ = 31;
public const short  ANGLE_BRACKET_COLON_BEGIN_ = 32;
public const short  ANGLE_BRACKET_COLON_END_ = 33;
public const short  BRACE_PERCENT_BEGIN_ = 34;
public const short  BRACE_PERCENT_END_ = 35;
public const short  BRACKET_PERCENT_BEGIN_ = 36;
public const short  BRACKET_PERCENT_END_ = 37;
public const short  PARENTHESES_PERCENT_BEGIN_ = 38;
public const short  PARENTHESES_PERCENT_END_ = 39;
public const short  ANGLE_BRACKET_PERCENT_BEGIN_ = 40;
public const short  ANGLE_BRACKET_PERCENT_END_ = 41;
public const short  COLON_COLON_ = 42;
public const short  DOT_ = 43;
public const short  POINTER_ = 44;
public const short  PERIOD_STAR_ = 45;
public const short  POINTER_STAR_ = 46;
public const short  IDENTIFIER_ = 47;
public const short  STRING_ = 48;
public const short  NUMBER_ = 49;
public const short  DOLLAR_STRING_ = 50;
public const short  COMMA_ = 51;
public const short  SEMI_ = 52;
public const short  END_OF_SLK_INPUT_ = 53;


public const short  NT_PROGRAM_ = 54;
public const short  NT_STATEMENTS_ = 55;
public const short  NT_STATEMENT_ = 56;
public const short  NT_OPERATOR_STATEMENT_1_ = 57;
public const short  NT_OPERATOR_STATEMENT_2_ = 58;
public const short  NT_OPERATOR_STATEMENT_COLON_ = 59;
public const short  NT_OPERATOR_STATEMENT_4_ = 60;
public const short  NT_OPERATOR_STATEMENT_5_ = 61;
public const short  NT_OPERATOR_STATEMENT_6_ = 62;
public const short  NT_OPERATOR_STATEMENT_7_ = 63;
public const short  NT_OPERATOR_STATEMENT_8_ = 64;
public const short  NT_OPERATOR_STATEMENT_9_ = 65;
public const short  NT_OPERATOR_STATEMENT_10_ = 66;
public const short  NT_OPERATOR_STATEMENT_11_ = 67;
public const short  NT_OPERATOR_STATEMENT_12_ = 68;
public const short  NT_OPERATOR_STATEMENT_13_ = 69;
public const short  NT_OPERATOR_STATEMENT_14_ = 70;
public const short  NT_OPERATOR_STATEMENT_DESC_0_ = 71;
public const short  NT_OPERATOR_STATEMENT_DESC_1_ = 72;
public const short  NT_OPERATOR_STATEMENT_DESC_ASSIGNMENT_OR_QUESTION_COLON_ = 73;
public const short  NT_OPERATOR_STATEMENT_DESC_2_ = 74;
public const short  NT_OPERATOR_STATEMENT_DESC_COLON_ = 75;
public const short  NT_OPERATOR_STATEMENT_DESC_3_ = 76;
public const short  NT_OPERATOR_STATEMENT_DESC_4_ = 77;
public const short  NT_OPERATOR_STATEMENT_DESC_5_ = 78;
public const short  NT_OPERATOR_STATEMENT_DESC_6_ = 79;
public const short  NT_OPERATOR_STATEMENT_DESC_7_ = 80;
public const short  NT_OPERATOR_STATEMENT_DESC_8_ = 81;
public const short  NT_OPERATOR_STATEMENT_DESC_9_ = 82;
public const short  NT_OPERATOR_STATEMENT_DESC_10_ = 83;
public const short  NT_OPERATOR_STATEMENT_DESC_11_ = 84;
public const short  NT_OPERATOR_STATEMENT_DESC_12_ = 85;
public const short  NT_OPERATOR_STATEMENT_DESC_13_ = 86;
public const short  NT_OPERATOR_STATEMENT_DESC_14_ = 87;
public const short  NT_OPERATOR_STATEMENT_DESC_15_ = 88;
public const short  NT_FUNCTION_STATEMENT_ = 89;
public const short  NT_FUNCTION_STATEMENT_DESC_ = 90;
public const short  NT_FUNCTION_CALLS_ = 91;
public const short  NT_FUNCTION_EX_CALL_ = 92;
public const short  NT_FUNCTION_EX_CALL_SPECIAL_ = 93;
public const short  NT_NULLABLE_FUNCTION_PARAMS_ = 94;
public const short  NT_FUNCTION_PARAMS_ = 95;
public const short  NT_PARENTHESES_PARAMS_ = 96;
public const short  NT_MEMBER_ = 97;
public const short  NT_MEMBER_PARAM_ = 98;
public const short  NT_MEMBER_PARAM_DETAIL_ = 99;
public const short  NT_FUNCTION_ID_ = 100;
public const short  NT_SEP_ = 101;
public const short  NT_SEP_STATEMENT_STAR_ = 102;
public const short  NT_OP_TOKEN_0_OPERATOR_STATEMENT_1_STAR_ = 103;
public const short  NT_OPERATOR_STATEMENT_DESC_ASSIGNMENT_OR_QUESTION_COLON_OPT_ = 104;
public const short  NT_OP_TOKEN_2_OPERATOR_STATEMENT_2_OPT_ = 105;
public const short  NT_OP_TOKEN_COLON_OPERATOR_STATEMENT_COLON_OPT_ = 106;
public const short  NT_OP_TOKEN_3_OPERATOR_STATEMENT_4_STAR_ = 107;
public const short  NT_OP_TOKEN_4_OPERATOR_STATEMENT_5_STAR_ = 108;
public const short  NT_OP_TOKEN_5_OPERATOR_STATEMENT_6_STAR_ = 109;
public const short  NT_OP_TOKEN_6_OPERATOR_STATEMENT_7_STAR_ = 110;
public const short  NT_OP_TOKEN_7_OPERATOR_STATEMENT_8_STAR_ = 111;
public const short  NT_OP_TOKEN_8_OPERATOR_STATEMENT_9_STAR_ = 112;
public const short  NT_OP_TOKEN_9_OPERATOR_STATEMENT_10_STAR_ = 113;
public const short  NT_OP_TOKEN_10_OPERATOR_STATEMENT_11_STAR_ = 114;
public const short  NT_OP_TOKEN_11_OPERATOR_STATEMENT_12_STAR_ = 115;
public const short  NT_OP_TOKEN_12_OPERATOR_STATEMENT_13_STAR_ = 116;
public const short  NT_OP_TOKEN_13_OPERATOR_STATEMENT_14_STAR_ = 117;
public const short  NT_OP_TOKEN_14_OPERATOR_STATEMENT_14_OPT_ = 118;
public const short  NT_OP_TOKEN_15_FUNCTION_STATEMENT_STAR_ = 119;
public const short  NT_FUNCTION_EX_CALL_STAR_ = 120;
public const short  NT_FUNCTION_EX_CALL_2_STAR_ = 121;
public const short  NT_NULLABLE_FUNCTION_PARAMS_OPT_ = 122;
public const short  NT_NULLABLE_FUNCTION_PARAMS_2_OPT_ = 123;
public const short  NT_NULLABLE_FUNCTION_PARAMS_3_OPT_ = 124;
public const short  NT_NULLABLE_FUNCTION_PARAMS_4_OPT_ = 125;
public const short  NT_NULLABLE_FUNCTION_PARAMS_5_OPT_ = 126;
public const short  NT_NULLABLE_FUNCTION_PARAMS_6_OPT_ = 127;
public const short  NT_NULLABLE_FUNCTION_PARAMS_7_OPT_ = 128;
public const short  NT_NULLABLE_FUNCTION_PARAMS_8_OPT_ = 129;
public const short  NT_NULLABLE_FUNCTION_PARAMS_9_OPT_ = 130;
public const short  NT_NULLABLE_FUNCTION_PARAMS_10_OPT_ = 131;
public const short  NT_NULLABLE_FUNCTION_PARAMS_11_OPT_ = 132;
public const short  NT_NULLABLE_FUNCTION_PARAMS_12_OPT_ = 133;
public const short  NT_NULLABLE_FUNCTION_PARAMS_13_OPT_ = 134;
public const short  NT_NULLABLE_FUNCTION_PARAMS_14_OPT_ = 135;
public const short  NT_NULLABLE_FUNCTION_PARAMS_15_OPT_ = 136;
public const short  NT_NULLABLE_FUNCTION_PARAMS_16_OPT_ = 137;
public const short  NT_NULLABLE_FUNCTION_PARAMS_17_OPT_ = 138;


};


}